import Head from "next/head";

export default function avneeshDark() {
  return (
    <div className="bg-gray-900 flex h-screen items-center justify-center px-16">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="relative w-full max-w-lg">
        <div className="absolute top-0 -left-4 w-72 h-72 bg-purple-300 rounded-full mix-blend-lighten filter blur-lg opacity-25 animate-blob"></div>
        <div className="absolute top-0 -right-4 w-72 h-72 bg-yellow-300 rounded-full mix-blend-lighten filter blur-lg opacity-25 animate-blob animation-delay-2000"></div>
        <div className="absolute left-20 -bottom-8 w-72 h-72 bg-pink-300 rounded-full mix-blend-lighten filter blur-lg opacity-25 animate-blob animation-delay-4000"></div>
        <div>
          <div className="transform hover:scale-110 duration-200 backdrop-filter backdrop-blur-2xl bg-gray-700 border-2 border-gray-500 bg-opacity-1 rounded-xl relative flex flex-col m-5 p-10 cursor-ponter items-center cursor-pointer">
            <h1 className="text-gray-300">Dummy text</h1>
          </div>
          <div className="transform hover:scale-110 duration-200 backdrop-filter backdrop-blur-2xl bg-gray-700 border-2 border-gray-500 bg-opacity-1 rounded-xl relative flex flex-col m-5 p-10 cursor-ponter items-center cursor-pointer">
            <h1 className="text-gray-300">Dummy text</h1>
          </div>
          <div className="transform hover:scale-110 duration-200 backdrop-filter backdrop-blur-2xl bg-gray-700 border-2 border-gray-500 bg-opacity-1 rounded-xl relative flex flex-col m-5 p-10 cursor-ponter items-center cursor-pointer">
            <h1 className="text-gray-300">Dummy text</h1>
          </div>
        </div>
      </div>
    </div>
  );
}
