import Head from "next/head";
import Image from "next/image";

function playground() {
  return (
    <div>
      <Head>
        <title>Playground Blurry Animated BG Shapes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-gray-100 min-h-screen flex items-center justify-center px-16">
        <div className="relative w-full max-w-lg">
          <div className="absolute top-0 -left-4 w-72 h-72 bg-purple-300 rounded-full mix-blend-multiply filter blur-2xl opacity-1 animate-blobtwo"></div>
          <div className="absolute top-0 -right-4 w-72 h-72 bg-yellow-300 rounded-full mix-blend-multiply filter blur-2xl opacity-1 animate-blobtwo animation-delay-2000"></div>
          <div className="absolute -bottom-8 left-20  w-72 h-72 bg-pink-300 rounded-full mix-blend-multiply filter blur-2xl opacity-1 animate-blobtwo animation-delay-4000"></div>
          <div className="m-8 relative space-y-4 opacity-0">
            <div className="p-5 bg-white rounded-lg flex items-center justify-between space-x-8">
              <div className="flex-1">
                <div className="h-4 w-48 bg-gray-300 rounded"></div>
              </div>
              <div className="w-24 h-6 rounded-lg bg-purple-300"></div>
            </div>
            <div className="p-5 bg-white rounded-lg flex items-center justify-between space-x-8">
              <div className="flex-1">
                <div className="h-4 w-49 bg-gray-300 rounded"></div>
              </div>
              <div className="w-24 h-6 rounded-lg bg-yellow-300"></div>
            </div>
            <div className="p-5 bg-white rounded-lg flex items-center justify-between space-x-8">
              <div className="flex-1">
                <div className="h-4 w-48 bg-gray-300 rounded"></div>
              </div>
              <div className="w-24 h-6 rounded-lg bg-pink-300"></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

export default playground;
